# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-26 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologyNews', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kr',
            fields=[
                ('title', models.CharField(max_length=256, verbose_name='\u6807\u9898')),
                ('summary', models.CharField(max_length=256, verbose_name='\u7b80\u4ecb')),
                ('extraction_tags', models.CharField(max_length=256, verbose_name='\u5206\u7c7b')),
                ('column_name', models.CharField(max_length=256, verbose_name='\u6807\u7b7e')),
                ('cover', models.CharField(max_length=256, verbose_name='\u56fe\u7247\u94fe\u63a5')),
                ('published_at', models.CharField(max_length=256, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('id', models.IntegerField(db_index=True, primary_key=True, serialize=False, verbose_name='id')),
            ],
            options={
                'verbose_name': '36kr',
                'verbose_name_plural': '36kr',
            },
        ),
        migrations.DeleteModel(
            name='YouDao',
        ),
    ]
