# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-29 17:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('technologyNews', '0003_svinsight'),
    ]

    operations = [
        migrations.DeleteModel(
            name='svinsight',
        ),
    ]
