# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-29 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('technologyNews', '0004_delete_svinsight'),
    ]

    operations = [
        migrations.CreateModel(
            name='svinsight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='\u6807\u9898')),
                ('summary', models.CharField(max_length=256, verbose_name='\u7b80\u4ecb')),
                ('tags', models.CharField(max_length=256, verbose_name='\u5206\u7c7b')),
                ('cover', models.CharField(max_length=256, verbose_name='\u56fe\u7247\u94fe\u63a5')),
                ('add_time', models.CharField(max_length=256, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('url', models.CharField(max_length=256, verbose_name='url')),
            ],
            options={
                'verbose_name': '\u7845\u8c37\u5bc6\u63a2',
                'verbose_name_plural': '\u7845\u8c37\u5bc6\u63a2',
            },
        ),
    ]
