# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-01-26 15:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TengXun',
            fields=[
                ('title', models.CharField(max_length=256, null=True, verbose_name='\u6807\u9898')),
                ('platform', models.CharField(max_length=256, null=True, verbose_name='\u5e73\u53f0')),
                ('type', models.CharField(max_length=256, null=True, verbose_name='\u7c7b\u578b')),
                ('url', models.CharField(max_length=256, null=True, verbose_name='\u5185\u5bb9\u94fe\u63a5')),
                ('imageurl', models.CharField(max_length=256, null=True, verbose_name='\u56fe\u7247\u94fe\u63a5')),
                ('audiourl', models.CharField(max_length=256, null=True, verbose_name='\u97f3\u9891\u94fe\u63a5')),
                ('videourl', models.CharField(max_length=256, null=True, verbose_name='\u89c6\u9891\u94fe\u63a5')),
                ('time', models.CharField(max_length=256, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('id', models.IntegerField(db_index=True, default='', primary_key=True, serialize=False, verbose_name='id')),
            ],
            options={
                'verbose_name': '\u817e\u8baf\u65b0\u95fb',
                'verbose_name_plural': '\u817e\u8baf\u65b0\u95fb',
            },
        ),
        migrations.CreateModel(
            name='WangYi',
            fields=[
                ('title', models.CharField(max_length=256, null=True, verbose_name='\u6807\u9898')),
                ('platform', models.CharField(max_length=256, null=True, verbose_name='\u5e73\u53f0')),
                ('type', models.CharField(max_length=256, null=True, verbose_name='\u7c7b\u578b')),
                ('url', models.CharField(max_length=256, null=True, verbose_name='\u5185\u5bb9\u94fe\u63a5')),
                ('imageurl', models.CharField(max_length=256, null=True, verbose_name='\u56fe\u7247\u94fe\u63a5')),
                ('audiourl', models.CharField(max_length=256, null=True, verbose_name='\u97f3\u9891\u94fe\u63a5')),
                ('videourl', models.CharField(max_length=256, null=True, verbose_name='\u89c6\u9891\u94fe\u63a5')),
                ('time', models.CharField(max_length=256, null=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('id', models.IntegerField(db_index=True, default='', primary_key=True, serialize=False, verbose_name='id')),
            ],
            options={
                'verbose_name': '\u7f51\u6613\u65b0\u95fb',
                'verbose_name_plural': '\u7f51\u6613\u65b0\u95fb',
            },
        ),
    ]
